export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const RETURN_BOOK = 'RETURN_BOOK';
export const GET_TRANSACTIONS_FOR_USER = "GET_TRANSACTIONS_FOR_USER"
export const TRANSACTION_ERROR = "TRANSACTION_ERROR"